controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - iiwa_joint_1
      - iiwa_joint_2
      - iiwa_joint_3
      - iiwa_joint_4
      - iiwa_joint_5
      - iiwa_joint_6
      - iiwa_joint_7
  - name: fake_gripper_controller
    type: $(arg fake_execution_type)
    joints:
      - finger_joint_revolute
initial:  # Define initial robot poses.
  - group: arm
    pose: home
  - group: gripper
    pose: close